# Generated by Django 4.2.11 on 2024-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_address_item_agency_employee_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
